class Table14CarRecept {
  String TCarID;
  String BookingRefNo;
  String Source;
  String Supplier;
  String PickupLocation;
  String PickupAddress;
  String PickupDate;
  String TicketCode;
  String DropoffLocation;
  String DropoffAddress;
  String DropoffDate;
  String CarName;
  String Cartype;
  String LeadDriver;
  String DriverDOB;
  String AdditionalDriver;
  String PNRNumber;
  String ConfirmationNo;
  String CarGroup;
  String CarStatus;
  String SupplierPaymentDate;
  String SupplierCurrency;
  String AdditinoalReffNo;
  String PayatSupplier;
  String Luggage;
  String Includes;
  String Excludes;
  String FreeText1;
  String CarGroup1;
  String Luggage1;
  String PickupDtt;
  String DropoffDtt;
  String PickupTime;
  String DropoffTime;

  Table14CarRecept({
    required this.TCarID,
    required this.BookingRefNo,
    required this.Source,
    required this.Supplier,
    required this.PickupLocation,
    required this.PickupAddress,
    required this.PickupDate,
    required this.TicketCode,
    required this.DropoffLocation,
    required this.DropoffAddress,
    required this.DropoffDate,
    required this.CarName,
    required this.Cartype,
    required this.LeadDriver,
    required this.DriverDOB,
    required this.AdditionalDriver,
    required this.PNRNumber,
    required this.ConfirmationNo,
    required this.CarGroup,
    required this.CarStatus,
    required this.SupplierPaymentDate,
    required this.SupplierCurrency,
    required this.AdditinoalReffNo,
    required this.PayatSupplier,
    required this.Luggage,
    required this.Includes,
    required this.Excludes,
    required this.FreeText1,
    required this.CarGroup1,
    required this.Luggage1,
    required this.PickupDtt,
    required this.DropoffDtt,
    required this.PickupTime,
    required this.DropoffTime,
  });

  factory Table14CarRecept.fromJson(Map<String, dynamic> json) {
    return Table14CarRecept(
      TCarID: json['TCarID'].toString(),
      BookingRefNo: json['BookingRefNo'].toString(),
      Source: json['Source'].toString(),
      Supplier: json['Supplier'].toString(),
      PickupLocation: json['PickupLocation'].toString(),
      PickupAddress: json['PickupAddress'].toString(),
      PickupDate: json['PickupDate'].toString(),
      TicketCode: json['TicketCode'].toString(),
      DropoffLocation: json['DropoffLocation'].toString(),
      DropoffAddress: json['DropoffAddress'].toString(),
      DropoffDate: json['DropoffDate'].toString(),
      CarName: json['CarName'].toString(),
      Cartype: json['Cartype'].toString(),
      LeadDriver: json['LeadDriver'].toString(),
      DriverDOB: json['DriverDOB'].toString(),
      AdditionalDriver: json['AdditionalDriver'].toString(),
      PNRNumber: json['PNRNumber'].toString(),
      ConfirmationNo: json['ConfirmationNo'].toString(),
      CarGroup: json['CarGroup'].toString(),
      CarStatus: json['CarStatus'].toString(),
      SupplierPaymentDate: json['SupplierPaymentDate'].toString(),
      SupplierCurrency: json['SupplierCurrency'].toString(),
      AdditinoalReffNo: json['AdditinoalReffNo'].toString(),
      PayatSupplier: json['PayatSupplier'].toString(),
      Luggage: json['Luggage'].toString(),
      Includes: json['Includes'].toString(),
      Excludes: json['Excludes'].toString(),
      FreeText1: json['FreeText1'].toString(),
      CarGroup1: json['CarGroup1'].toString(),
      Luggage1: json['Luggage1'].toString(),
      PickupDtt: json['PickupDtt'].toString(),
      DropoffDtt: json['DropoffDtt'].toString(),
      PickupTime: json['PickupTime'].toString(),
      DropoffTime: json['DropoffTime'].toString(),
    );
  }
}
