class ManageStaffModel {
  String slNo;
  String staffId;
  String staffName;
  String departmentId;
  String mobile;
  String email;
  String staffImage;
  String joinedDate;
  String status;
  String createdDate;
  String username;
  String password;
  String accountName;
  String accountNumber;
  String bankName;
  String branch;
  String bankCode;
  String accountType;
  String branchId;
  String countryId;
  String cbSelectAll;
  String designationId;
  String primaryRoleId;
  String secondaryRoleId;
  String teamId;
  String staffCode;
  String nickName;
  String countryId1;
  String code1;
  String area1;
  String phone1;
  String extern1;
  String countryId2;
  String code2;
  String area2;
  String phone2;
  String extern2;
  String cbApplyIP;
  String dailyBookingLimit;
  String cbDailyBookingLimit;
  String multireisenID;
  String pricelineID;
  String cbHandleEnquiry;
  String cbHandleVIP;
  String enquiryType;
  String userTypeId;
  String userId;
  String address;
  String city;
  String pincode;

  ManageStaffModel({
    required this.slNo,
    required this.staffId,
    required this.staffName,
    required this.departmentId,
    required this.mobile,
    required this.email,
    required this.staffImage,
    required this.joinedDate,
    required this.status,
    required this.createdDate,
    required this.username,
    required this.password,
    required this.accountName,
    required this.accountNumber,
    required this.bankName,
    required this.branch,
    required this.bankCode,
    required this.accountType,
    required this.branchId,
    required this.countryId,
    required this.cbSelectAll,
    required this.designationId,
    required this.primaryRoleId,
    required this.secondaryRoleId,
    required this.teamId,
    required this.staffCode,
    required this.nickName,
    required this.countryId1,
    required this.code1,
    required this.area1,
    required this.phone1,
    required this.extern1,
    required this.countryId2,
    required this.code2,
    required this.area2,
    required this.phone2,
    required this.extern2,
    required this.cbApplyIP,
    required this.dailyBookingLimit,
    required this.cbDailyBookingLimit,
    required this.multireisenID,
    required this.pricelineID,
    required this.cbHandleEnquiry,
    required this.cbHandleVIP,
    required this.enquiryType,
    required this.userTypeId,
    required this.userId,
    required this.address,
    required this.city,
    required this.pincode,
  });

  factory ManageStaffModel.fromJson(Map<String, dynamic> json) {
    return ManageStaffModel(
      slNo: json['SlNo'].toString(),
      staffId: json['StaffId'].toString(),
      staffName: json['StaffName'].toString(),
      departmentId: json['DepartmentId'].toString(),
      mobile: json['Mobile'].toString(),
      email: json['Email'].toString(),
      staffImage: json['StaffImage'].toString(),
      joinedDate: json['JoinedDate'].toString(),
      status: json['Status'].toString(),
      createdDate: json['CreatedDate'].toString(),
      username: json['Username'].toString(),
      password: json['Password'].toString(),
      accountName: json['AccountName'].toString(),
      accountNumber: json['AccountNumber'].toString(),
      bankName: json['BankName'].toString(),
      branch: json['Branch'].toString(),
      bankCode: json['BankCode'].toString(),
      accountType: json['AccountType'].toString(),
      branchId: json['BranchId'].toString(),
      countryId: json['CountryId'].toString(),
      cbSelectAll: json['CBSelectAll'].toString(),
      designationId: json['DesignationId'].toString(),
      primaryRoleId: json['PrimaryRoleId'].toString(),
      secondaryRoleId: json['SecondaryRoleId'].toString(),
      teamId: json['TeamId'].toString(),
      staffCode: json['StaffCode'].toString(),
      nickName: json['NickName'].toString(),
      countryId1: json['CountryId1'].toString(),
      code1: json['Code1'].toString(),
      area1: json['Area1'].toString(),
      phone1: json['Phone1'].toString(),
      extern1: json['Extern1'].toString(),
      countryId2: json['CountryId2'].toString(),
      code2: json['Code2'].toString(),
      area2: json['Area2'].toString(),
      phone2: json['Phone2'].toString(),
      extern2: json['Extern2'].toString(),
      cbApplyIP: json['CBApplyIP'].toString(),
      dailyBookingLimit: json['DailyBookingLimit'].toString(),
      cbDailyBookingLimit: json['CBDailyBookingLimit'].toString(),
      multireisenID: json['MultireisenID'].toString(),
      pricelineID: json['PricelineID'].toString(),
      cbHandleEnquiry: json['CBHandleEnquiry'].toString(),
      cbHandleVIP: json['CBHandleVIP'].toString(),
      enquiryType: json['EnquiryType'].toString(),
      userTypeId: json['UserTypeId'].toString(),
      userId: json['UserId'].toString(),
      address: json['Address'].toString(),
      city: json['City'].toString(),
      pincode: json['Pincode'].toString(),
    );
  }
}
