import 'dart:convert';

class ViewSubAgentModel {
  List<Tablee0> table0;
  List<Tableee1> table1;
  List<Tableee2> table2;
  List<Tableee3> table3;

  List<Tablee7> table7;
  ViewSubAgentModel({
    required this.table0,
    required this.table1,
    required this.table2,
    required this.table3,
    required this.table7,
  });
  factory ViewSubAgentModel.fromJson(Map<String, dynamic> json) {
    return ViewSubAgentModel(
      table0: (json['Table'] as List<dynamic>)
          .map((e) => Tablee0.fromJson(e as Map<String, dynamic>))
          .toList(),
      table1: (json['Table1'] as List<dynamic>)
          .map((e) => Tableee1.fromJson(e as Map<String, dynamic>))
          .toList(),
      table2: (json['Table2'] as List<dynamic>)
          .map((e) => Tableee2.fromJson(e as Map<String, dynamic>))
          .toList(),
      table3: (json['Table3'] as List<dynamic>)
          .map((e) => Tableee3.fromJson(e as Map<String, dynamic>))
          .toList(),
      table7: (json['Table7'] as List<dynamic>)
          .map((e) => Tablee7.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }
}

class Tablee0 {
  String subAgentId;
  String agentName;
  String dateOfOperation;
  String emailAddress;
  String cBDistributor;
  String branchId;
  String salesGroupId;
  String languageId;
  String businessCurrencyId;
  String addressLine1;
  String addressLine2;
  String addressLine3;
  String city;
  String state;
  String postCode;
  String countryId;
  String telephone;
  String mobile;
  String fax;
  String officeSpace;
  String businessType;
  String designaton;
  String contactMobile;
  String contactEmail;
  String websiteURL;
  String refrredby;
  String longitude;
  String latitude;
  String generalRemarks;
  String cBShowremark;
  String remarks;
  String subAgentLogo;
  String status;
  String dateCreated;
  String username;
  String password;
  String GSTNumber;
  String PANNumber;
  String AccountName;
  String AccountNumber;
  String IFSCCode;
  String BankName;
  String BankLocation;
  String UserTypeId;
  String UserId;
  String ApproveStatus;
  String RefreshPNR;
  String ViewPNR;
  String SeatMap;
  String backofficeFile;
  String importBooking;
  String salesReport;
  String issueTicket;
  String cancelBooking;
  String cancelTicket;
  String manageServices;
  String manageElement;
  String agencyId;
  String agencyBranchId;
  String flightMarkup;
  String hotelMarkup;
  String carMarkup;
  String sightSeeingMarkup;
  String busMarkup;
  String changeBooking;
  String viewTicket;
  String downloadDocument;
  String bookingOptions;
  String subAgentMembershipId;
  String subAgentId1;
  String vatNumber;
  String cbvatSelfBilling;
  String abtaNumber;
  String cbDirectDebitAgent;
  String iataNumber;
  String iataMember;
  String atolNumber;
  String cbChargeSafi;
  String cbChargeApc;
  String ttaNumber;
  String globalTravelGroup;
  String licenseNumber;
  String serviceTax;
  String panNo;
  String tanNo;
  String ntnNo;
  String cnpjNo;
  String cbAgentApplicationForm;
  String status1;
  String dateCreated1;
  String subAgentFinancialId;
  String subAgentId2;
  String gstNo;
  String gstUnitCode;
  String gstAgencyClassificationId;
  String gstHolderName;
  String gstAgencyName;
  String cbAddress;
  String gstAgencyAddress;
  String gstCountryId;
  String gstStateId;
  String gstCity;
  String gstContactNo;
  String gstHolderEmail;
  String gstPaymentId;
  String creditLimit;
  String creditLimitAlert;
  String cbDoNotSend;
  String tdsApplicable;
  String tdsExemption;
  String cbApplyServiceTax;
  String tempCreditLimit;
  String tempCreditLimitStartDate;
  String tempCreditLimitEndDate;
  String cbApplyTicketLimit;
  String dayTicketLimitGenValue;
  String propertyOwner;
  String guaranteeSigned;
  String reserveVolumeMonthly;
  String noofEmployees;
  String noofBranches;
  String status2;
  String dateCreated2;
  String subAgentPaymentId;
  String subAgentId3;
  String payPeriod;
  String payment;
  String annualTurnover;
  String status3;
  String dateCreated3;
  String subAgentB2B2CWebsiteId;
  String subAgentId4;
  String enableB2B2CWebsite;
  String flight;
  String hotel;
  String car;
  String insurance;
  String package;
  String sightseeing;
  String transfer;
  String dynamicSearch;
  String status4;
  String dateCreated4;
  String subAgentOtherDetailId;
  String subAgentId5;
  String manageBranches;
  String manageUsers;
  String manageRoles;
  String manageMarkups;
  String manageCreditCards;
  String gdsTerminal;
  String specialFlightFares;
  String importFlightPnrGds;
  String allowAutoTicket;
  String iitFare;
  String supplierCredentials;
  String pgCredentials;
  String b2BLogo;
  String allowAir;
  String status5;
  String dateCreated5;
  String operationDate;
  String creditLimitStartDate;
  String creditLimitEndDate;
  String interfaceFlight;
  String interfaceHotel;
  String interfaceCar;
  String interfaceInsurance;
  String interfacePackage;
  String interfaceSightseeing;
  String interfaceTransfer;
  String interfaceDynamicSearch;
  String enableB2B2CWebsite1;
  String websiteFlight;
  String websiteHotel;
  String websiteCar;
  String websiteInsurance;
  String websitePackage;
  String languages;
  String currency;
  String fax1;
  String websiteSightseeing;
  String websiteTransfer;
  String websiteDynamicSearch;
  String userTypeId1;
  String userId1;
  String name;
  String customerName;
  String refreshPnr1;
  String viewPnr1;
  String seatMap1;
  String backofficeFile1;
  String importBooking1;
  String salesReport1;
  String issueTicket1;
  String cancelBooking1;
  String cancelTicket1;
  String manageServices1;
  String manageElement1;
  String changeBooking1;
  String viewTicket1;
  String downloadDocument1;
  String bookingOptions1;
  String agencyId1;
  String agencyBranchId1;
  String country;
  String currencyCode;
  String agentType;
  String status6;
  String agencyBranchId2;
  String agencyBranchName;
  String saleGroup;
  String payPeriodName;
  String paymentName;

  Tablee0({
    required this.subAgentId,
    required this.agentName,
    required this.dateOfOperation,
    required this.emailAddress,
    required this.cBDistributor,
    required this.branchId,
    required this.salesGroupId,
    required this.languageId,
    required this.businessCurrencyId,
    required this.addressLine1,
    required this.addressLine2,
    required this.addressLine3,
    required this.city,
    required this.state,
    required this.postCode,
    required this.countryId,
    required this.telephone,
    required this.mobile,
    required this.fax,
    required this.officeSpace,
    required this.businessType,
    required this.designaton,
    required this.contactMobile,
    required this.contactEmail,
    required this.websiteURL,
    required this.refrredby,
    required this.longitude,
    required this.latitude,
    required this.generalRemarks,
    required this.cBShowremark,
    required this.remarks,
    required this.subAgentLogo,
    required this.status,
    required this.dateCreated,
    required this.username,
    required this.password,
    required this.GSTNumber,
    required this.PANNumber,
    required this.AccountName,
    required this.AccountNumber,
    required this.IFSCCode,
    required this.BankName,
    required this.BankLocation,
    required this.UserTypeId,
    required this.UserId,
    required this.ApproveStatus,
    required this.RefreshPNR,
    required this.ViewPNR,
    required this.SeatMap,
    required this.backofficeFile,
    required this.importBooking,
    required this.salesReport,
    required this.issueTicket,
    required this.cancelBooking,
    required this.cancelTicket,
    required this.manageServices,
    required this.manageElement,
    required this.agencyId,
    required this.agencyBranchId,
    required this.flightMarkup,
    required this.hotelMarkup,
    required this.carMarkup,
    required this.sightSeeingMarkup,
    required this.busMarkup,
    required this.changeBooking,
    required this.viewTicket,
    required this.downloadDocument,
    required this.bookingOptions,
    required this.subAgentMembershipId,
    required this.subAgentId1,
    required this.vatNumber,
    required this.cbvatSelfBilling,
    required this.abtaNumber,
    required this.cbDirectDebitAgent,
    required this.iataNumber,
    required this.iataMember,
    required this.atolNumber,
    required this.cbChargeSafi,
    required this.cbChargeApc,
    required this.ttaNumber,
    required this.globalTravelGroup,
    required this.licenseNumber,
    required this.serviceTax,
    required this.panNo,
    required this.tanNo,
    required this.ntnNo,
    required this.cnpjNo,
    required this.cbAgentApplicationForm,
    required this.status1,
    required this.dateCreated1,
    required this.subAgentFinancialId,
    required this.subAgentId2,
    required this.gstNo,
    required this.gstUnitCode,
    required this.gstAgencyClassificationId,
    required this.gstHolderName,
    required this.gstAgencyName,
    required this.cbAddress,
    required this.gstAgencyAddress,
    required this.gstCountryId,
    required this.gstStateId,
    required this.gstCity,
    required this.gstContactNo,
    required this.gstHolderEmail,
    required this.gstPaymentId,
    required this.creditLimit,
    required this.creditLimitAlert,
    required this.cbDoNotSend,
    required this.tdsApplicable,
    required this.tdsExemption,
    required this.cbApplyServiceTax,
    required this.tempCreditLimit,
    required this.tempCreditLimitStartDate,
    required this.tempCreditLimitEndDate,
    required this.cbApplyTicketLimit,
    required this.dayTicketLimitGenValue,
    required this.propertyOwner,
    required this.guaranteeSigned,
    required this.reserveVolumeMonthly,
    required this.noofEmployees,
    required this.noofBranches,
    required this.status2,
    required this.dateCreated2,
    required this.subAgentPaymentId,
    required this.subAgentId3,
    required this.payPeriod,
    required this.payment,
    required this.annualTurnover,
    required this.status3,
    required this.dateCreated3,
    required this.subAgentB2B2CWebsiteId,
    required this.subAgentId4,
    required this.enableB2B2CWebsite,
    required this.flight,
    required this.hotel,
    required this.car,
    required this.insurance,
    required this.package,
    required this.sightseeing,
    required this.transfer,
    required this.dynamicSearch,
    required this.status4,
    required this.dateCreated4,
    required this.subAgentOtherDetailId,
    required this.subAgentId5,
    required this.manageBranches,
    required this.manageUsers,
    required this.manageRoles,
    required this.manageMarkups,
    required this.manageCreditCards,
    required this.gdsTerminal,
    required this.specialFlightFares,
    required this.importFlightPnrGds,
    required this.allowAutoTicket,
    required this.iitFare,
    required this.supplierCredentials,
    required this.pgCredentials,
    required this.b2BLogo,
    required this.allowAir,
    required this.status5,
    required this.dateCreated5,
    required this.operationDate,
    required this.creditLimitStartDate,
    required this.creditLimitEndDate,
    required this.interfaceFlight,
    required this.interfaceHotel,
    required this.interfaceCar,
    required this.interfaceInsurance,
    required this.interfacePackage,
    required this.interfaceSightseeing,
    required this.interfaceTransfer,
    required this.interfaceDynamicSearch,
    required this.enableB2B2CWebsite1,
    required this.websiteFlight,
    required this.websiteHotel,
    required this.websiteCar,
    required this.websiteInsurance,
    required this.websitePackage,
    required this.languages,
    required this.currency,
    required this.fax1,
    required this.websiteSightseeing,
    required this.websiteTransfer,
    required this.websiteDynamicSearch,
    required this.userTypeId1,
    required this.userId1,
    required this.name,
    required this.customerName,
    required this.refreshPnr1,
    required this.viewPnr1,
    required this.seatMap1,
    required this.backofficeFile1,
    required this.importBooking1,
    required this.salesReport1,
    required this.issueTicket1,
    required this.cancelBooking1,
    required this.cancelTicket1,
    required this.manageServices1,
    required this.manageElement1,
    required this.changeBooking1,
    required this.viewTicket1,
    required this.downloadDocument1,
    required this.bookingOptions1,
    required this.agencyId1,
    required this.agencyBranchId1,
    required this.country,
    required this.currencyCode,
    required this.agentType,
    required this.status6,
    required this.agencyBranchId2,
    required this.agencyBranchName,
    required this.saleGroup,
    required this.payPeriodName,
    required this.paymentName,
  });
  factory Tablee0.fromJson(Map<String, dynamic> json) {
    return Tablee0(
      subAgentId: json['SubAgentID'].toString(),
      agentName: json['AgentName'].toString(),
      dateOfOperation: json['DateofOperation'].toString(),
      emailAddress: json['EmailAddress'].toString(),
      cBDistributor: json['CBDistributor'].toString(),
      branchId: json['BranchId'].toString(),
      salesGroupId: json['SalesGroupId'].toString(),
      languageId: json['LanguageId'].toString(),
      businessCurrencyId: json['BusinessCurrencyId'].toString(),
      addressLine1: json['AddressLine1'].toString(),
      addressLine2: json['AddressLine2'].toString(),
      addressLine3: json['AddressLine3'].toString(),
      city: json['City'].toString(),
      state: json['State'].toString(),
      postCode: json['PostCode'].toString(),
      countryId: json['CountryId'].toString(),
      telephone: json['Telephone'].toString(),
      mobile: json['Mobile'].toString(),
      fax: json['Fax'].toString(),
      officeSpace: json['OfficeSpace'].toString(),
      businessType: json['BusinessType'].toString(),
      designaton: json['Designaton'].toString(),
      contactMobile: json['ContactMobile'].toString(),
      contactEmail: json['ContactEmail'].toString(),
      websiteURL: json['WebsiteURL'].toString(),
      refrredby: json['Refrredby'].toString(),
      longitude: json['Longitude'].toString(),
      latitude: json['Latitude'].toString(),
      generalRemarks: json['GeneralRemarks'].toString(),
      cBShowremark: json['CBShowremark'].toString(),
      remarks: json['Remarks'].toString(),
      subAgentLogo: json['SubAgentLogo'].toString(),
      status: json['Status'].toString(),
      dateCreated: json['DateCreated'].toString(),
      username: json['Username'].toString(),
      password: json['Password'].toString(),
      GSTNumber: json['GSTNumber'].toString(),
      PANNumber: json['PANNumber'].toString(),
      AccountName: json['AccountName'].toString(),
      AccountNumber: json['AccountNumber'].toString(),
      IFSCCode: json['IFSCCode'].toString(),
      BankName: json['BankName'].toString(),
      BankLocation: json['BankLocation'].toString(),
      UserTypeId: json['UserTypeId'].toString(),
      UserId: json['UserId'].toString(),
      ApproveStatus: json['ApproveStatus'].toString(),
      RefreshPNR: json['RefreshPNR'].toString(),
      ViewPNR: json['ViewPNR'].toString(),
      SeatMap: json['SeatMap'].toString(),
      backofficeFile: json['BackofficeFile'].toString(),
      importBooking: json['ImportBooking'].toString(),
      salesReport: json['SalesReport'].toString(),
      issueTicket: json['IssueTicket'].toString(),
      cancelBooking: json['CancelBooking'].toString(),
      cancelTicket: json['CancelTicket'].toString(),
      manageServices: json['ManageServices'].toString(),
      manageElement: json['ManageElement'].toString(),
      agencyId: json['AgencyId'].toString(),
      agencyBranchId: json['AgencyBranchId'].toString(),
      flightMarkup: json['FlightMarkup'].toString(),
      hotelMarkup: json['HotelMarkup'].toString(),
      carMarkup: json['CarMarkup'].toString(),
      sightSeeingMarkup: json['SightSeeingMarkup'].toString(),
      busMarkup: json['BusMarkup'].toString(),
      changeBooking: json['ChangeBooking'].toString(),
      viewTicket: json['ViewTicket'].toString(),
      downloadDocument: json['DownloadDocument'].toString(),
      bookingOptions: json['BookingOptions'].toString(),
      subAgentMembershipId: json['SubAgentMembershipID'].toString(),
      subAgentId1: json['SubAgentID1'].toString(),
      vatNumber: json['VATNumber'].toString(),
      cbvatSelfBilling: json['CBVATSelfBilling'].toString(),
      abtaNumber: json['ABTANumber'].toString(),
      cbDirectDebitAgent: json['CBDirectDebitAgent'].toString(),
      iataNumber: json['IATANumber'].toString(),
      iataMember: json['IATAMember'].toString(),
      atolNumber: json['ATOLNumber'].toString(),
      cbChargeSafi: json['CBChargeSafi'].toString(),
      cbChargeApc: json['CBChargeApc'].toString(),
      ttaNumber: json['TTANumber'].toString(),
      globalTravelGroup: json['GlobalTravelGroup'].toString(),
      licenseNumber: json['LicenseNumber'].toString(),
      serviceTax: json['ServiceTax'].toString(),
      panNo: json['PANNo'].toString(),
      tanNo: json['TANNo'].toString(),
      ntnNo: json['NTNNo'].toString(),
      cnpjNo: json['CNPJNo'].toString(),
      cbAgentApplicationForm: json['CBAgentApplicationForm'].toString(),
      status1: json['Status1'].toString(),
      dateCreated1: json['DateCreated1'].toString(),
      subAgentFinancialId: json['SubAgentFinancialID'].toString(),
      subAgentId2: json['SubAgentID2'].toString(),
      gstNo: json['GSTNo'].toString(),
      gstUnitCode: json['GSTUnitCode'].toString(),
      gstAgencyClassificationId: json['GSTAgencyClassificationId'].toString(),
      gstHolderName: json['GSTHolderName'].toString(),
      gstAgencyName: json['GSTAgencyName'].toString(),
      cbAddress: json['CBAddress'].toString(),
      gstAgencyAddress: json['GSTAgencyAddress'].toString(),
      gstCountryId: json['GSTCountryId'].toString(),
      gstStateId: json['GSTStateId'].toString(),
      gstCity: json['GSTCity'].toString(),
      gstContactNo: json['GSTContactNo'].toString(),
      gstHolderEmail: json['GSTHolderEmail'].toString(),
      gstPaymentId: json['GSTPaymentId'].toString(),
      creditLimit: json['CreditLimit'].toString(),
      creditLimitAlert: json['CreditLimitAlert'].toString(),
      cbDoNotSend: json['CBDoNotSend'].toString(),
      tdsApplicable: json['TDSApplicable'].toString(),
      tdsExemption: json['TDSExemption'].toString(),
      cbApplyServiceTax: json['CBApplyServiceTax'].toString(),
      tempCreditLimit: json['TempCreditLimit'].toString(),
      tempCreditLimitStartDate: json['TempCreditLimitStartDate'].toString(),
      tempCreditLimitEndDate: json['TempCreditLimitEndDate'].toString(),
      cbApplyTicketLimit: json['CBApplyTicketLimit'].toString(),
      dayTicketLimitGenValue: json['DayTicketLimitGenValue'].toString(),
      propertyOwner: json['PropertyOwner'].toString(),
      guaranteeSigned: json['GuaranteeSigned'].toString(),
      reserveVolumeMonthly: json['ReserveVolumeMonthly'].toString(),
      noofEmployees: json['NoofEmployees'].toString(),
      noofBranches: json['NoofBranches'].toString(),
      status2: json['Status2'].toString(),
      dateCreated2: json['DateCreated2'].toString(),
      subAgentPaymentId: json['SubAgentPaymentID'].toString(),
      subAgentId3: json['SubAgentID3'].toString(),
      payPeriod: json['PayPeriod'].toString(),
      payment: json['Payment'].toString(),
      annualTurnover: json['AnnualTurnover'].toString(),
      status3: json['Status3'].toString(),
      dateCreated3: json['DateCreated3'].toString(),
      subAgentB2B2CWebsiteId: json['SubAgentB2B2CWebsiteID'].toString(),
      subAgentId4: json['SubAgentID4'].toString(),
      enableB2B2CWebsite: json['EnableB2B2CWebsite'].toString(),
      flight: json['Flight'].toString(),
      hotel: json['Hotel'].toString(),
      car: json['Car'].toString(),
      insurance: json['Insurance'].toString(),
      package: json['Package'].toString(),
      sightseeing: json['Sightseeing'].toString(),
      transfer: json['Transfer'].toString(),
      dynamicSearch: json['DynamicSearch'].toString(),
      status4: json['Status4'].toString(),
      dateCreated4: json['DateCreated4'].toString(),
      subAgentOtherDetailId: json['SubAgentOtherDetailID'].toString(),
      subAgentId5: json['SubAgentID5'].toString(),
      manageBranches: json['ManageBranches'].toString(),
      manageUsers: json['ManageUsers'].toString(),
      manageRoles: json['ManageRoles'].toString(),
      manageMarkups: json['ManageMarkups'].toString(),
      manageCreditCards: json['ManageCreditCards'].toString(),
      gdsTerminal: json['GDSTerminal'].toString(),
      specialFlightFares: json['SpecialFlightFares'].toString(),
      importFlightPnrGds: json['ImportFlightPNRGDS'].toString(),
      allowAutoTicket: json['AllowAutoTicket'].toString(),
      iitFare: json['IITFare'].toString(),
      supplierCredentials: json['SupplierCredentials'].toString(),
      pgCredentials: json['PGCredentials'].toString(),
      b2BLogo: json['B2BLogo'].toString(),
      allowAir: json['AllowAir'].toString(),
      status5: json['Status5'].toString(),
      dateCreated5: json['DateCreated5'].toString(),
      operationDate: json['OperationDate'].toString(),
      creditLimitStartDate: json['CreditLimitStartDate'].toString(),
      creditLimitEndDate: json['CreditLimitEndDate'].toString(),
      interfaceFlight: json['InterfaceFlight'].toString(),
      interfaceHotel: json['InterfaceHotel'].toString(),
      interfaceCar: json['InterfaceCar'].toString(),
      interfaceInsurance: json['InterfaceInsurance'].toString(),
      interfacePackage: json['InterfacePackage'].toString(),
      interfaceSightseeing: json['InterfaceSightseeing'].toString(),
      interfaceTransfer: json['InterfaceTransfer'].toString(),
      interfaceDynamicSearch: json['InterfaceDynamicSearch'].toString(),
      enableB2B2CWebsite1: json['EnableB2B2CWebsite1'].toString(),
      websiteFlight: json['WebsiteFlight'].toString(),
      websiteHotel: json['WebsiteHotel'].toString(),
      websiteCar: json['WebsiteCar'].toString(),
      websiteInsurance: json['WebsiteInsurance'].toString(),
      websitePackage: json['WebsitePackage'].toString(),
      languages: json['Languages'].toString(),
      currency: json['Currency'].toString(),
      fax1: json['Fax1'].toString(),
      websiteSightseeing: json['WebsiteSightseeing'].toString(),
      websiteTransfer: json['WebsiteTransfer'].toString(),
      websiteDynamicSearch: json['WebsiteDynamicSearch'].toString(),
      userTypeId1: json['UserTypeId1'].toString(),
      userId1: json['UserId1'].toString(),
      name: json['Name'].toString(),
      customerName: json['CustomerName'].toString(),
      refreshPnr1: json['RefreshPNR1'].toString(),
      viewPnr1: json['ViewPNR1'].toString(),
      seatMap1: json['SeatMap1'].toString(),
      backofficeFile1: json['BackofficeFile1'].toString(),
      importBooking1: json['ImportBooking1'].toString(),
      salesReport1: json['SalesReport1'].toString(),
      issueTicket1: json['IssueTicket1'].toString(),
      cancelBooking1: json['CancelBooking1'].toString(),
      cancelTicket1: json['CancelTicket1'].toString(),
      manageServices1: json['ManageServices1'].toString(),
      manageElement1: json['ManageElement1'].toString(),
      changeBooking1: json['ChangeBooking1'].toString(),
      viewTicket1: json['ViewTicket1'].toString(),
      downloadDocument1: json['DownloadDocument1'].toString(),
      bookingOptions1: json['BookingOptions1'].toString(),
      agencyId1: json['AgencyId1'].toString(),
      agencyBranchId1: json['AgencyBranchId1'].toString(),
      country: json['Country'].toString(),
      currencyCode: json['CurrencyCode'].toString(),
      agentType: json['AgentType'].toString(),
      status6: json['Status6'].toString(),
      agencyBranchId2: json['AgencyBranchId2'].toString(),
      agencyBranchName: json['AgencyBranchName'].toString(),
      saleGroup: json['SaleGroup'].toString(),
      payPeriodName: json['PayPeriodName'].toString(),
      paymentName: json['PaymentName'].toString(),
    );
  }
}

class Tableee1 {
  String subAgentSalesId;
  String subAgentId;
  String emailAddress;
  String telephone;
  String mobile;
  String contactName;
  String status;
  String dateCreated;

  Tableee1({
    required this.subAgentSalesId,
    required this.subAgentId,
    required this.emailAddress,
    required this.telephone,
    required this.mobile,
    required this.contactName,
    required this.status,
    required this.dateCreated,
  });

  factory Tableee1.fromJson(Map<String, dynamic> json) {
    return Tableee1(
      subAgentSalesId: json['SubAgentSalesID'].toString(),
      subAgentId: json['SubAgentID'].toString(),
      emailAddress: json['EmailAddress'].toString(),
      telephone: json['Telephone'].toString(),
      mobile: json['Mobile'].toString(),
      contactName: json['ContactName'].toString(),
      status: json['Status'].toString(),
      dateCreated: json['DateCreated'].toString(),
    );
  }
}

class Tableee2 {
  String subAgentBankId;
  String subAgentId;
  String bankName;
  String bankAddress;
  String bankSwiftCode;
  String bankPhoneNo;
  String bankFaxNo;
  String bankAccountNo;
  String status;
  String dateCreated;

  Tableee2({
    required this.subAgentBankId,
    required this.subAgentId,
    required this.bankName,
    required this.bankAddress,
    required this.bankSwiftCode,
    required this.bankPhoneNo,
    required this.bankFaxNo,
    required this.bankAccountNo,
    required this.status,
    required this.dateCreated,
  });

  factory Tableee2.fromJson(Map<String, dynamic> json) {
    return Tableee2(
      subAgentBankId: json['SubAgentBankID'].toString(),
      subAgentId: json['SubAgentID'].toString(),
      bankName: json['BankName'].toString(),
      bankAddress: json['BankAddress'].toString(),
      bankSwiftCode: json['BankSwiftCode'].toString(),
      bankPhoneNo: json['BankPhoneNo'].toString(),
      bankFaxNo: json['BankFaxNo'].toString(),
      bankAccountNo: json['BankAccountNo'].toString(),
      status: json['Status'].toString(),
      dateCreated: json['DateCreated'].toString(),
    );
  }
}

class Tableee3 {
  int subAgentId;
  int cardType;
  String cardTypeName;
  String card;
  String cardCompany;
  String cardNumber;
  String nameOnTheCard;
  String expiryDate;
  String validateDate;
  String cvvNo;

  Tableee3({
    required this.subAgentId,
    required this.cardType,
    required this.cardTypeName,
    required this.card,
    required this.cardCompany,
    required this.cardNumber,
    required this.nameOnTheCard,
    required this.expiryDate,
    required this.validateDate,
    required this.cvvNo,
  });

  factory Tableee3.fromJson(Map<String, dynamic> json) {
    return Tableee3(
      subAgentId: json['SubAgentId'],
      cardType: json['CardType'],
      cardTypeName: json['CardTypeName'],
      card: json['Card'],
      cardCompany: json['CardCompany'],
      cardNumber: json['CardNumber'],
      nameOnTheCard: json['NameontheCard'],
      expiryDate: json['ExpiryDate'],
      validateDate: json['ValidateDate'],
      cvvNo: json['CVVNo'],
    );
  }
}

class Tablee7 {
  final int subAgentDocumentID;
  final int subAgentID;
  final String documentTitle;
  final String documentFile;
  final int status;
  final String dateCreated;

  Tablee7({
    required this.subAgentDocumentID,
    required this.subAgentID,
    required this.documentTitle,
    required this.documentFile,
    required this.status,
    required this.dateCreated,
  });

  factory Tablee7.fromJson(Map<String, dynamic> json) {
    return Tablee7(
      subAgentDocumentID: json['SubAgentDocumentID'],
      subAgentID: json['SubAgentID'],
      documentTitle: json['DocumentTitle'],
      documentFile: json['DocumentFile'],
      status: json['Status'],
      dateCreated: json['DateCreated'],
    );
  }
}
