class CarBookingModel {
  String tCarID;
  String bookingRefNo;
  String source;
  String supplier;
  String pickupLocation;
  String pickupAddress;
  String pickupDate;
  String dropoffLocation;
  String dropoffAddress;
  String dropoffDate;
  String carName;
  String carType;
  String leadDriver;
  String driverDOB;
  String additionalDriver;
  String pnrNumber;
  String confirmationNo;
  String carGroup;
  String carStatus;
  String supplierPaymentDate;
  String supplierCurrency;
  String additionalRefNo;
  String payAtSupplier;
  String luggage;
  String includes;
  String excludes;
  String freeText1;
  String carGroup1;
  String luggage1;
  String pickupDtt;
  String dropoffDtt;
  String pickupTime;
  String dropoffTime;

  CarBookingModel({
    required this.tCarID,
    required this.bookingRefNo,
    required this.source,
    required this.supplier,
    required this.pickupLocation,
    required this.pickupAddress,
    required this.pickupDate,
    required this.dropoffLocation,
    required this.dropoffAddress,
    required this.dropoffDate,
    required this.carName,
    required this.carType,
    required this.leadDriver,
    required this.driverDOB,
    required this.additionalDriver,
    required this.pnrNumber,
    required this.confirmationNo,
    required this.carGroup,
    required this.carStatus,
    required this.supplierPaymentDate,
    required this.supplierCurrency,
    required this.additionalRefNo,
    required this.payAtSupplier,
    required this.luggage,
    required this.includes,
    required this.excludes,
    required this.freeText1,
    required this.carGroup1,
    required this.luggage1,
    required this.pickupDtt,
    required this.dropoffDtt,
    required this.pickupTime,
    required this.dropoffTime,
  });

  factory CarBookingModel.fromJson(Map<String, dynamic> json) {
    return CarBookingModel(
      tCarID: json['TCarID'].toString(),
      bookingRefNo: json['BookingRefNo'].toString(),
      source: json['Source'].toString(),
      supplier: json['Supplier'].toString(),
      pickupLocation: json['PickupLocation'].toString(),
      pickupAddress: json['PickupAddress'].toString(),
      pickupDate: json['PickupDate'].toString(),
      dropoffLocation: json['DropoffLocation'].toString(),
      dropoffAddress: json['DropoffAddress'].toString(),
      dropoffDate: json['DropoffDate'].toString(),
      carName: json['CarName'].toString(),
      carType: json['Cartype'].toString(),
      leadDriver: json['LeadDriver'].toString(),
      driverDOB: json['DriverDOB'].toString(),
      additionalDriver: json['AdditionalDriver'].toString(),
      pnrNumber: json['PNRNumber'].toString(),
      confirmationNo: json['ConfirmationNo'].toString(),
      carGroup: json['CarGroup'].toString(),
      carStatus: json['CarStatus'].toString(),
      supplierPaymentDate: json['SupplierPaymentDate'].toString(),
      supplierCurrency: json['SupplierCurrency'].toString(),
      additionalRefNo: json['AdditinoalReffNo'].toString(),
      payAtSupplier: json['PayatSupplier'].toString(),
      luggage: json['Luggage'].toString(),
      includes: json['Includes'].toString(),
      excludes: json['Excludes'].toString(),
      freeText1: json['FreeText1'].toString(),
      carGroup1: json['CarGroup1'].toString(),
      luggage1: json['Luggage1'].toString(),
      pickupDtt: json['PickupDtt'].toString(),
      dropoffDtt: json['DropoffDtt'].toString(),
      pickupTime: json['PickupTime'].toString(),
      dropoffTime: json['DropoffTime'].toString(),
    );
  }
}
